# ============================
# servux Configuration  ini config file
# ============================

# Global Settings
[global]
max_body_size = 1048576
timeout = 3000
keep_alive = true

# Error Pages
[error_pages]
400 = ./error_pages/400.html
403 = ./error_pages/403.html
404 = ./error_pages/404.html
405 = ./error_pages/405.html
413 = ./error_pages/413.html
500 = ./error_pages/500.html


[server]
server_name = localhost,127.0.0.1
host = 127.0.0.1
ports = 8080,8000,8002
root = ./www


# Routes
[route:main:root]
path = /
methods = GET
index = index.html
autoindex = false

[route:main:ok]
path = /ok
methods = GET
root = ./www
index = ok
autoindex = false

[route:main:x]
path = /x
methods = GET
root = ./www
index = x
autoindex = false

[route:main:static]
path = /static
methods = GET
root = ./www/static
autoindex = false

[route:main:uploads]
path = /uploads
methods = GET,POST,DELETE
upload_dir = ./www/uploads
autoindex = true
max_file_size = 5242880

[route:main:api]
path = /api
methods = GET, POST
root = ./www/cgi-bin
cgi_extension = .py
cgi_executor = /usr/bin/python3

[route:main:cgi_bin]
path = /cgi-bin
methods = POST, GET
cgi_extension = .py
cgi_executor = /usr/bin/python3
root = ./www/cgi-bin


[route:main:old_redirect]
path = /old-path
redirect_status = 301
redirect_target = /api/env.py

[route:main:temp_redirect]
path = /temp
redirect_status = 302
redirect_target = https://example.com

# Session & Cookie Settings
[session]
enabled = true
timeout = 1800
cookie_name = LOCALSERVER_SESSION
secure = false
http_only = false
